name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run verification script
      run: python verify.py
    
    - name: Run tests with pytest
      run: |
        pip install pytest
        if [ -d "tests" ]; then
          python -m pytest tests/ -v
        else
          echo "No tests directory found"
        fi